Small changes

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -2,10 +2,13 @@
 #
 # bootstrap installs things.
 
+set -e
+set -u
+set -o
+
+UNAMER=$(uname -r)
 cd "$(dirname "$0")/.."
 DOTFILES_ROOT=$(pwd -P)
-
-set -e
 
 echo ''
 
@@ -47,6 +50,65 @@ setup_gitconfig () {
 
     success 'gitconfig'
   fi
+}
+
+install_zsh () {
+  success "..Installing oh-my-zsh"
+
+
+  if [ "$FLAVOUR" == Debian ]; then
+    # sudo apt update
+    # sudo apt -y upgrade
+    # sudo apt -y qinstall zsh
+    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
+    success "..zsh installed oh-my-zsh Debain system."
+  elif [ "$FLAVOUR" == osx ]; then
+    # /usr/bin/ruby -e "$(curl -fsSL https://raw.zshhubusercontent.com/Homebrew/install/master/install)"
+    # brew doctor
+    # brew install zsh
+    #### THIS NEEDS TO BE RELOOKED AT - THE GIT REPO SEEMS TO HAVE CHANGED!!!
+    git clone --quiet https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
+    sudo sh -c "echo $(which zsh) >> /etc/shells" && chsh -s $(which zsh)
+    success '..zsh installed on Mac'
+  fi
+  
+
+  mkdir -p ~/.oh-my-zsh/custom/themes
+  if [[ -x /usr/bin/curl ]]; then
+   curl https://raw.githubusercontent.com/denysdovhan/spaceship-zsh-theme/master/spaceship.zsh --output ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme --silent
+   success ".. Themes Downloaded"
+  elif [[ -x /usr/bin/wget ]]; then
+    wget –quiet –output-document ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme https://raw.githubusercontent.com/denysdovhan/spaceship-zsh-theme/master/spaceship.zsh
+    success "..Theme Downloaded"
+  else
+     fail "[ERROR] Curl or wget not installed"
+  fi
+
+  cd ~/.oh-my-zsh/themes
+  curl -O "https://github.com/andrewconnell/osx-install/raw/master/app-settings/iterm/bullet-train.zsh-theme"
+  git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
+
+  cd ~/.oh-my-zsh/plugins
+  git clone https://github.com/sbodiu-pivotal/fly-zsh-autocomplete-plugin.git fly
+ 
+  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
+  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
+
+  # Testing for the migration from powerlevel9k to powerlevel10k
+  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k
+
+  
+  # pip3 install --user powerline-status
+  # pip3 install --user git+git://github.com/powerline/powerline
+
+  git clone --depth 1 https://github.com/ryanoasis/nerd-fonts.git ~/.nerd-fonts/
+  ~/.nerd-fonts/install.sh
+
+#   wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
+#   wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
+
+  # install shell integration & utilities
+  curl -L https://iterm2.com/misc/install_shell_integration.sh | bash
 }
 
 
@@ -137,20 +199,54 @@ install_dotfiles () {
   done
 }
 
-setup_gitconfig
-install_dotfiles
+# What system am I running on?
+if [ "$(uname -s)" == "Darwin" ]; then
+    success "Detected Darwin (OSX) based operating system"
+    FLAVOUR="osx"
+elif [ -x /usr/bin/apt-get  ]; then
+# elif [ -f /etc/debian_version ]; then
+# Might look at using if [[ -x /usr/bin/apt-get ]]; then
+    success "Detected Debian/apt based operating system"
+    FLAVOUR="Debian"
+elif [ -f /etc/redhat-release ]; then
+# Might look to change to use elif [[ -x /usr/bin/yum ]]; then
+    success "Detected RetHat variant (RHEL/Centos) operating system"
+    FLAVOUR="Redhat"
+else
+  fail "[ERROR] Cannot detect operating system"
 
-# If we're on a Mac, let's install and setup homebrew.
-if [ "$(uname -s)" == "Darwin" ]
-then
-  info "installing dependencies"
-  if source bin/dot | while read -r data; do info "$data"; done
-  then
-    success "dependencies installed"
-  else
-    fail "error installing dependencies"
-  fi
 fi
 
-echo ''
-echo '  All installed!'
+info "Setup zsh"
+install_zsh
+success "..ZSH Setup"
+info "Setup dotfiles"
+install_dotfiles
+success "..dotfiles Setup"
+
+
+success "..install packages"
+
+# # find the installers and run them iteratively
+# find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
+source ${DOTFILES_ROOT}/script/install
+
+success "Complete"
+
+# setup_gitconfig
+# install_dotfiles
+
+# # If we're on a Mac, let's install and setup homebrew.
+# if [ "$(uname -s)" == "Darwin" ]
+# then
+#   info "installing dependencies"
+#   if source bin/dot | while read -r data; do info "$data"; done
+#   then
+#     success "dependencies installed"
+#   else
+#     fail "error installing dependencies"
+#   fi
+# fi
+
+# echo ''
+# echo '  All installed!'
